on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - 'development'
          - 'production'
      server_name:
        description: 'Specify the Server Name'
        required: true
        type: string
      server_region:
        description: 'Server Region'
        required: true
        default: 'US East'
        type: choice
        options:
          - 'US East'
          - 'East US 2'
          - 'Central US'
          - 'UK South'
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to specified environment
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment."
          echo "Deploying Servername: ${{ github.event.inputs.server_name }}"
          if ${{ github.event.inputs.release_version }}; then
            echo "Using Azure Region: ${{ github.event.inputs.server_region }}"
          fi
