on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - 'development'
          - 'production'
      server_name:
        description: 'Specify the Server Name'
        required: true
        type: string
      server_region:
        description: 'Server Region'
        required: true
        default: 'US East'
        type: choice
        options:
          - 'US East'
          - 'East US 2'
          - 'Central US'
          - 'UK South'
          
